more _POSIX_VDISABLE fuckery (fuck GNU glibc, a̲g̲a̲i̲n̲!):
Act 1:	glibc on GNU/kFreeBSD, in contrast to proper MidnightBSD (for
	example), defines _POSIX_VDISABLE to something not a valid C
	præprocessor token:

	../../sh.h:399:7: error: missing binary operator before token "char"
	  399 | #elif _POSIX_VDISABLE == -1
	      |       ^~~~~~~~~~~~~~~

	Verified on lemon.debian.net (kfreebsd-amd64 porter box).
	This actively breaks the *intended* way of using this macro
	but (I suppose…) that’s GNU for you…

Act 2:	A gem shared by https://stackoverflow.com/a/50186064/2171120

	“I looked at some old systems in the Unix tree. All of
	 Minix 1.5 (1989), Linux 0.96c (1992), and 4.4BSD (1993)
	 have _POSIX_VDISABLE defined and not -1.”

	So rip out the ifdef and assume it’s defined-and-not-disabled
	until someone porting encounters an OS which doesn’t?

Act 3:	Of course, Linux klibc (nor the Linux uapi headers) define
	_POSIX_VDISABLE at all. I mean it’s not like this is part
	of the kernel tty API or something (ha ha only serious)…

Therefore we’re currently ending up with:
• if _POSIX_VDISABLE is defined assume it’s not -1
• if _POSIX_VDISABLE is not defined use “the old BSD value” (0377,
  but as unsigned int because cc_t is unsigned, and as hex number
  because the days octal (outside of chmod/umask…) made sense have
  died with PDP endianness), which also fits with EO not being in
  use in UTF-8 o̲r̲ EBCDIC…

If this ever reaches an operating environment where these don’t hold
true and where the fallback to 0xFFU (which -1 would map to as well)
causes trouble, we’ll need to do as pdksh did and store _POSIX_VDISABLE
in a variable (though, of what type…) possibly using fpathconf(2) also.
Intermediate chance may be a mirtoconf test for whether _POSIX_VDISABLE
is defined and not -1 and restoring the pre-1.954 macros except checking
the mirtoconf output first… (still no fpathconf(2) but meh)

tl;dr: portability was fucking hard before the modern fuckers who are
probably younger than many systems mksh runs on invented sarding more
catdamned breakage…